// Generated by scripts/build-food-info.mjs on 2026-09-17. Do not edit by hand.
// Diet and cuisine: OpenStreetMap (ODbL). Google place ids only: ratings are fetched live, never stored.

export type Diet = 'vegan' | 'vegetarian' | 'gluten_free';

export interface FoodInfo {
  /** OpenStreetMap object the tags come from */
  osm: string;
  diet?: Diet[];
  /** OSM cuisine values, e.g. polish, coffee_shop */
  cuisine?: string[];
  /** Google Places id; storable indefinitely under Google's policies */
  googlePlaceId?: string;
}

export const FOOD_INFO: Record<string, FoodInfo> = {
  'wierzynek': { osm: 'node/475613615', cuisine: ['polish'] },
  'noworolski': { osm: 'node/3789279757', cuisine: ['regional'] },
  'jama-michalika': { osm: 'node/3320712471' },
  'milk-bar-temida': { osm: 'node/2348490970', cuisine: ['polish'] },
  'massolit': { osm: 'node/3519353826' },
  'judah-square': { osm: 'way/1021761893' },
  'stary-kleparz': { osm: 'way/25070800' },
  'pod-jaszczurami': { osm: 'node/475613654' },
  'piwnica-pod-baranami': { osm: 'node/475387327' },
  'harris-jazz': { osm: 'node/475387322' },
  'u-muniaka': { osm: 'node/490986424' },
  'prozak': { osm: 'node/4734733123' },
  'house-of-beer': { osm: 'node/3784847876' },
  'multi-qlti': { osm: 'node/3784821422' },
  'wodka-bar': { osm: 'node/4281228581' },
  'alchemia': { osm: 'node/773107379', diet: ['vegan', 'vegetarian'], cuisine: ['breakfast'] },
  'mleczarnia': { osm: 'node/2026934622' },
  'hevre': { osm: 'node/6010850389' },
  'eszeweria': { osm: 'node/2135508856' },
  'piekny-pies': { osm: 'node/5945604779' },
  'drukarnia': { osm: 'node/1497915909' },
  'klub-studio': { osm: 'way/231815725' },
  'klub-kwadrat': { osm: 'node/2122790276' },
};
